# Generated by Django 5.1.4 on 2024-12-05 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lala_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Iur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('useless_data', models.CharField(default='Useless Data', max_length=100)),
                ('lalaland', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lala_app.lalaland')),
            ],
        ),
        migrations.RenameModel(
            old_name='EmptyTable',
            new_name='Stm',
        ),
        migrations.DeleteModel(
            name='UselessTable',
        ),
    ]
