# Generated by Django 5.1.4 on 2024-12-05 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lala_app', '0002_iur_rename_emptytable_stm_delete_uselesstable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iur',
            name='useless_data',
        ),
        migrations.AddField(
            model_name='iur',
            name='name',
            field=models.CharField(default='i nkow', max_length=255),
        ),
        migrations.AlterField(
            model_name='iur',
            name='lalaland',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iur_instances', to='lala_app.lalaland'),
        ),
        migrations.AlterField(
            model_name='lalaland',
            name='message',
            field=models.CharField(max_length=255),
        ),
    ]
