# Generated by Django 5.1.4 on 2024-12-05 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lala_app', '0003_remove_iur_useless_data_iur_name_alter_iur_lalaland_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iur',
            name='lalaland',
        ),
        migrations.RemoveField(
            model_name='iur',
            name='name',
        ),
        migrations.AddField(
            model_name='iur',
            name='useless_data',
            field=models.CharField(default='Useless Data', max_length=100),
        ),
        migrations.AlterField(
            model_name='lalaland',
            name='message',
            field=models.CharField(default='Hello World from Lalaland!', max_length=100),
        ),
    ]
